### ISSUE TITLE
Support python 3

### ISSUE THREAD

**Issue by i-keliukh** [Samsung/Universum#253]
pip is going to stop providing updates for python 2 soon. Because of that Universum has to support python 3.

**Comment by i-savynikh** [comment]
Python 2.7 will not be maintained past 2020.
Decided to migrate to python3 and stop python2 supporting for Universum.

Decided to use python3.7 first because of p4python dependency.
Reason: p4python installed using pip without 'python dev' package for python3.7 only (on moment of migration – 2020 January). For other version of python3 it requires access to [perforce ftp server](ftp://ftp.perforce.com/) and appropriate python dev package.

**Comment by k-dovgan** [comment]
Done by #418
