### ISSUE TITLE
Unexpected and undocumented response of universum.analyzers.uncrustify

### ISSUE THREAD

**Issue by iakoff** [Samsung/Universum#607]
## Description
During implementation of code style check on CI according to documentation https://universum.readthedocs.io/en/latest/code_report.html#uncrustify
unexpected and undocumented response of universum.analyzers.uncrustify appear.

## Steps to reproduce
Univerusm run command line:
$ python3.7 -u -m universum --p4-client MYWORKSPACE --out-type term --p4-force-clean  -lo file --report-to-review -rof -rsu --swarm-server-url https://review.unplugged.com  --no-archive  --vcs-type p4 --no-diff

step in CONFIGS_DUMP.txt
{'name': 'uncrustifyMandatory Code Style check ', 'code_report': True, 'command': 'python3.8 -m universum.analyzers.uncrustify --files /home/ciuser/workspace/Precommit/temp --cfg-file /home/ciuser/workspace/Precommit/temp/code_style/_cpp.cfg --filter-regex .*//.(?:c|cpp|h|hpp) --result-file ${CODE_REPORT_FILE} --output-directory uncrustify', 'report_artifacts': 'uncrustify/*.html', 'if_env_set': 'STRICT_CODE_STYLE == YES'},

## Expected result
Clear documented output according to Documentation

## Actual result
$ /usr/bin/python3.8 -m universum.analyzers.uncrustify --files /home/ciuser/workspace/Precommit/temp --cfg-file /home/ciuser/workspace/Precommit/temp/code_style/_cpp.cfg --filter-regex '.*//.(?:c|cpp|h|hpp)' --result-file '${CODE_REPORT_FILE}' --output-directory uncrustify
stderr: Traceback (most recent call last):
stderr:   File "/usr/lib/python3.8/runpy.py", line 194, in _run_module_as_main
stderr:     return _run_code(code, main_globals, None,
stderr:   File "/usr/lib/python3.8/runpy.py", line 87, in _run_code
stderr:     exec(code, run_globals)
stderr:   File "/home/ciuser/.local/lib/python3.8/site-packages/universum/analyzers/uncrustify.py", line 199, in <module>
stderr:     exit_code = main()
stderr:   File "/home/ciuser/.local/lib/python3.8/site-packages/universum/analyzers/uncrustify.py", line 195, in main
stderr:     return analyze.execute()
stderr:   File "/home/ciuser/.local/lib/python3.8/site-packages/universum/analyzers/uncrustify.py", line 174, in execute
stderr:     files = self.parse_files()
stderr:   File "/home/ciuser/.local/lib/python3.8/site-packages/universum/analyzers/uncrustify.py", line 108, in parse_files
stderr:     for file_name in self.settings.file_names:
stderr: AttributeError: 'Namespace' object has no attribute 'file_names'
Module sh got exit code 1

## Environment
Focal
Python 3.8.5
Universum 0.19.6

## Additional context
Uncrustify tools not installed before this execution, but appropriate error expected,

**Comment by o-andrieiev** [comment]
The problem is caused by incorrect split of single PR for "analyzers refactoring" into multiple separate PR - one (#594 ) for common functions and another (#596 ) for uncrustify. Argument "--files" used to populate "file_names" internal parameter, which got renamed to "file_list" in #594, however analyzers.uncrustify was not updated accordingly in #594.
Commit #596 resolves this issue and adds corresponding tests, so we just need to release it.
Unfortunately, analyzers.uncrustify module didn't have any tests prior to #596 so this issues has not been found in time.
Furthermore due to the container nature of "Namespace" type, mypy could not detect such mismatch between populated and used parameters.
