### ISSUE TITLE
module universum.analyzers.uncrustify can't find files to check

### ISSUE THREAD

**Issue by iakoff** [Samsung/Universum#612]
## Description
module universum.analyzers.uncrustify can't find files to check

## Steps to reproduce
both steps executed from folder /home/ciuser/Precommit/temp/
$ /usr/bin/python3.8 -m universum.analyzers.uncrustify --cfg-file /home/ciuser/Precommit/temp/code_style/_cpp.cfg --filter-regex '.*//.(?:c|cpp)' --result-file '${CODE_REPORT_FILE}' --output-directory uncrustify --files .
stderr: Please provide at least one file for analysis
Module sh got exit code 2

$ /usr/bin/python3.8 -m universum.analyzers.uncrustify --cfg-file /home/ciuser/Precommit/temp/code_style/_cpp.cfg --result-file '${CODE_REPORT_FILE}' --output-directory uncrustify --files src/test.c
Module sh got exit code 1

## Expected result
Expected exit with 0 code and code style report to swarm.

## Actual result
exit with unclear failure and no code style report to swarm 

## Environment
Focal
Python 3.8.5
Universum 0.19.7

**Comment by o-andrieiev** [comment]
After some investigation, the original reporter could no longer reproduce the issue.
The analysis of the log files showed that while code_report=True flah is present the reporting step is omitted completely.
This behaviour was deemed impossible before.
One possible causes for this issue is misuse of configuration API. To investigate further, the config file should be rewritten to leave only the code report Step data.

**Comment by o-andrieiev** [comment]
@iakoff please close as unreproducible or provide additional debug data as requested
